### ISSUE TITLE
Error if one AUR package depends on another AUR package

### ISSUE THREAD

**Issue by recolic** [zocker-160/aur-builder#1]
If the AUR package to be built depends on another AUR package, it would report an failure. 

```
➜  tmp sudo docker run --rm --name builder --user builder --net host -v (pwd)/build:/results zocker160/aur-builder yaourt
Cloning into '/build/source'...
found 8 cores
==> Making package: yaourt 1.9-1 (Wed 23 Jun 2021 08:12:38 AM UTC)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: package-query>=1.8
==> ERROR: 'pacman' failed to install missing dependencies.
==> Missing dependencies:
  -> package-query>=1.8
==> Checking buildtime dependencies...
==> ERROR: Could not resolve all dependencies.
cp: cannot stat '/build/source/*.pkg.tar.*': No such file or directory
```

It seems that we need some code to build the dependencies recursively.

**Comment by zocker-160** [comment]
yes I can confirm this is a limitation of the current approach, I will look into it.

**Comment by zocker-160** [comment]
@recolic 
it should be fixed, building `yaourt` did work for me now

OT: keep in mind, that you are missing a `$` in your command, otherwise the `(pwd)` might not work

**Comment by recolic** [comment]
Oh. I'm using fish instead of bash. It doesn't matter.
thanks for your work!

Jun 23, 2021 22:25:41 zocker-160 ***@***.***>:

**Comment by zocker-160** [comment]
> Oh. I'm using fish instead of bash. It doesn't matter.

ahh ok understood then forget what I said ;)
